export default function decorate(block) {
  // 1. Get all direct children of the block (rows, as generated by AEM/EDS)
  const rows = [...block.children];

  // 2. If there is nothing inside the block, stop
  if (rows.length === 0) return;

const quoteTextEl = block.querySelector('[data-aue-prop="quoteText"]');
const authorEl = block.querySelector('[data-aue-prop="author"]');

  // 5. Create the semantic wrapper elements
  const figure = document.createElement('figure');
  figure.classList.add('quote'); // used by quote.css

  const blockquote = document.createElement('blockquote');
  const figcaption = document.createElement('figcaption');

  // 6. Fill the quote text
  if (quoteTextEl) {
    blockquote.innerHTML = quoteTextEl.innerHTML || quoteTextEl.textContent;
  }

  // 7. Fill the author text
  if (authorEl) {
    figcaption.textContent = authorEl.textContent;
  }

  // 8. Assemble the final DOM structure
  figure.append(blockquote, figcaption);

  // 9. Replace original block content with our custom markup
  block.innerHTML = '';
  block.append(figure);
}