export default function decorate(block) {
  // 1. Get all direct children of the block (rows, as generated by AEM/EDS)
  const rows = [...block.children];

  // 2. If there is nothing inside the block, stop
  if (rows.length === 0) return;

  // 3. First row: try to find the quote text element
  const quoteTextEl =
    rows[0].querySelector('[data-richtext-prop="quoteText"]') ||
    rows[0].querySelector('p') ||
    rows[0].querySelector('div');

  // 4. Second row (optional): try to find the author element
  const authorRow = rows[1];
  const authorEl = authorRow
    ? authorRow.querySelector('[data-aue-prop="author"]') ||
      authorRow.querySelector('p') ||
      authorRow.querySelector('div')
    : null;

  // 5. Create the semantic wrapper elements
  const figure = document.createElement('figure');
  figure.classList.add('quote'); // used by quote.css

  const blockquote = document.createElement('blockquote');
  const figcaption = document.createElement('figcaption');

  // 6. Fill the quote text
  if (quoteTextEl) {
    blockquote.innerHTML = quoteTextEl.innerHTML || quoteTextEl.textContent;
  }

  // 7. Fill the author text
  if (authorEl) {
    figcaption.textContent = authorEl.textContent;
  }

  // 8. Assemble the final DOM structure
  figure.append(blockquote, figcaption);

  // 9. Replace original block content with our custom markup
  block.innerHTML = '';
  block.append(figure);
}